name: Meshery Build and Releaser (edge)
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - ".github/**"
      - "install/**"
jobs:
  build:
    name: Docker build and push
    if: github.repository == 'meshery/meshery' && github.event_name != 'pull_request' && success()
    env:
      RELEASE_CHANNEL: "edge"
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch latest tag
        run: |
          echo "LATEST_TAG=$(curl --silent "https://api.github.com/repos/meshery/meshery/releases" | jq ' .[] | ."tag_name"' | sed -n 1p$'\n' | tr -d '"')" >> $GITHUB_ENV
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker edge build & tag
        run: |
          DOCKER_BUILDKIT=1 docker build -f install/docker/Dockerfile --no-cache -t ${{ secrets.IMAGE_NAME }}:edge-latest --build-arg TOKEN=${{ secrets.GLOBAL_TOKEN }} --build-arg GIT_COMMITSHA=${GITHUB_SHA::8} --build-arg GIT_VERSION=${{ env.LATEST_TAG }} --build-arg RELEASE_CHANNEL=${RELEASE_CHANNEL} .
          docker tag ${{ secrets.IMAGE_NAME }}:edge-latest ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::8}
          docker tag ${{ secrets.IMAGE_NAME }}:edge-latest ${{ secrets.IMAGE_NAME }}:edge-${{ env.LATEST_TAG }}
      - name: Docker edge push
        run: |
          docker push ${{ secrets.IMAGE_NAME }}:edge-latest
          docker push ${{ secrets.IMAGE_NAME }}:edge-${GITHUB_SHA::8}
          docker push ${{ secrets.IMAGE_NAME }}:edge-${{ env.LATEST_TAG }}

